server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MichaelZaleskovsky/QuestionaryConfig
          username: MichaelZaleskovsky
          password: mmz6776829
#          search-paths:#          - ItemService
#          - UserService
#          search-paths: itemservice, userservice
        encrypt:
          enabled: false